// Local fallback so the site still renders if the backend/DB isn't running.
// The real data comes from the Express + MongoDB API when available.

const img = (seed, w = 900, h = 1100) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const fallbackCollections = [
  {
    _id: "c1",
    title: "Stallions",
    slug: "stallions",
    description:
      "Powerful equine studies exploring movement, muscle and the untamed spirit of the horse.",
    image: img("nk-stallions", 1000, 1200),
  },
  {
    _id: "c2",
    title: "Figurative",
    slug: "figurative",
    description:
      "Human forms and portraits rendered in luminous colour, balancing harmony and chaos.",
    image: img("nk-figurative", 1000, 1200),
  },
  {
    _id: "c3",
    title: "Abstract",
    slug: "abstract",
    description:
      "Expressive abstractions where colour luminosity and contrast meet on canvas.",
    image: img("nk-abstract", 1000, 1200),
  },
];

export const fallbackProducts = [
  {
    _id: "p1",
    title: "Crimson Stallion",
    slug: "crimson-stallion",
    collectionSlug: "stallions",
    price: 85000,
    currency: "PKR",
    medium: "Oil on canvas",
    dimensions: "36 x 48 in",
    featured: true,
    inStock: true,
    description:
      "A brooding stallion emerges from a deep crimson field, capturing raw power and stillness.",
    images: [img("stallion-1"), img("stallion-1b")],
  },
  {
    _id: "p2",
    title: "Midnight Gallop",
    slug: "midnight-gallop",
    collectionSlug: "stallions",
    price: 92000,
    currency: "PKR",
    medium: "Oil on canvas",
    dimensions: "40 x 50 in",
    inStock: true,
    description: "Motion frozen in time as a dark horse charges through the night.",
    images: [img("stallion-2")],
  },
  {
    _id: "p3",
    title: "Golden Mane",
    slug: "golden-mane",
    collectionSlug: "stallions",
    price: 78000,
    currency: "PKR",
    medium: "Acrylic on canvas",
    dimensions: "30 x 40 in",
    inStock: true,
    description: "Warm golden light catches the flowing mane of a resting horse.",
    images: [img("stallion-3")],
  },
  {
    _id: "p4",
    title: "Quiet Gaze",
    slug: "quiet-gaze",
    collectionSlug: "figurative",
    price: 110000,
    currency: "PKR",
    medium: "Oil on canvas",
    dimensions: "24 x 36 in",
    featured: true,
    inStock: true,
    description: "An intimate portrait exploring the balance between harmony and chaos.",
    images: [img("figure-1")],
  },
  {
    _id: "p5",
    title: "Veiled Light",
    slug: "veiled-light",
    collectionSlug: "figurative",
    price: 98000,
    currency: "PKR",
    medium: "Oil on canvas",
    dimensions: "28 x 40 in",
    inStock: true,
    description: "Soft light falls across a contemplative figure.",
    images: [img("figure-2")],
  },
  {
    _id: "p6",
    title: "Reverie",
    slug: "reverie",
    collectionSlug: "figurative",
    price: 105000,
    currency: "PKR",
    medium: "Mixed media",
    dimensions: "30 x 42 in",
    inStock: true,
    description: "A dreamlike study of the human form in colour.",
    images: [img("figure-3")],
  },
  {
    _id: "p7",
    title: "Chaos & Harmony",
    slug: "chaos-and-harmony",
    collectionSlug: "abstract",
    price: 70000,
    currency: "PKR",
    medium: "Acrylic on canvas",
    dimensions: "36 x 36 in",
    featured: true,
    inStock: true,
    description: "Bold strokes collide and resolve into unexpected balance.",
    images: [img("abstract-1")],
  },
  {
    _id: "p8",
    title: "Luminous Field",
    slug: "luminous-field",
    collectionSlug: "abstract",
    price: 64000,
    currency: "PKR",
    medium: "Acrylic on canvas",
    dimensions: "32 x 44 in",
    inStock: true,
    description: "Layered colour creating depth and glow.",
    images: [img("abstract-2")],
  },
  {
    _id: "p9",
    title: "Fragments",
    slug: "fragments",
    collectionSlug: "abstract",
    price: 58000,
    currency: "PKR",
    medium: "Mixed media",
    dimensions: "28 x 38 in",
    inStock: true,
    description: "Broken forms reassembled into a quiet rhythm.",
    images: [img("abstract-3")],
  },
];
